import { Movie, PrimaryVibe, DreadIntensity } from './types';
import { EXTENDED_CURATED_MOVIES } from './data/extendedMovies';

export const TMDB_API_KEY = 'db7b89d2113d782e3f1769449fc380d5';
export const TMDB_BASE_URL = 'https://api.themoviedb.org/3';
export const IMAGE_BASE_URL = 'https://image.tmdb.org/t/p/w500';

export const APP_NAME = "DREADSWIPE";
export const APP_TAGLINE = "Craft over shock. Dread over jump scares. If it's not willing to rot from the inside, keep swiping.";
export const APP_PITCH = "Elevated dread with a body count. Craft over cheap scares — but never so arty it forgets to hurt.";

export interface VibeDefinition {
  id: PrimaryVibe;
  title: string;
  subtext: string;
  anchors: string[];
  color: string;
  iconName: string;
}

export const PRIMARY_VIBES: VibeDefinition[] = [
  {
    id: 'Elevated',
    title: 'Elevated',
    subtext: 'Horror that went to film school',
    anchors: ['The Substance', 'Hereditary', 'Smile', 'Barbarian'],
    color: 'from-amber-600 to-red-600',
    iconName: 'GraduationCap'
  },
  {
    id: 'Body Horror',
    title: 'Body Horror',
    subtext: 'Flesh is the argument',
    anchors: ['Titane', 'Martyrs', 'The Substance', 'Possession'],
    color: 'from-rose-600 to-red-900',
    iconName: 'Activity'
  },
  {
    id: 'Folk / Ritual',
    title: 'Folk / Ritual',
    subtext: "Something's wrong with this village",
    anchors: ['The Wailing', 'Midsommar', 'Kill List', 'Hagazussa'],
    color: 'from-emerald-700 to-stone-900',
    iconName: 'Trees'
  },
  {
    id: 'Prestige Crime',
    title: 'Prestige Crime',
    subtext: 'Violence as character study',
    anchors: ['A History of Violence', 'Zodiac', 'No Country for Old Men', 'Se7en'],
    color: 'from-slate-600 to-zinc-900',
    iconName: 'ShieldAlert'
  },
  {
    id: 'Cerebral Sci-Fi',
    title: 'Cerebral Sci-Fi',
    subtext: 'Bleak, contained, thinking too hard',
    anchors: ['Alien', 'Children of Men', 'Event Horizon', 'Under the Skin'],
    color: 'from-cyan-700 to-blue-950',
    iconName: 'Cpu'
  },
  {
    id: 'International Arthouse',
    title: 'International Arthouse',
    subtext: 'Subtitles, no apologies',
    anchors: ['Oldboy', 'The Handmaiden', 'When Evil Lurks', 'La Haine'],
    color: 'from-purple-700 to-indigo-950',
    iconName: 'Globe'
  },
  {
    id: 'Sicko Mode',
    title: 'Sicko Mode',
    subtext: 'Full commitment, no mercy',
    anchors: ['Martyrs', 'The Substance', 'The House That Jack Built', 'The Sadness'],
    color: 'from-red-600 via-rose-700 to-black',
    iconName: 'Flame'
  }
];

export const DREAD_LEVELS: Record<DreadIntensity, { label: string; description: string; color: string; skulls: string }> = {
  1: { label: 'Unsettling', description: 'Creeping atmospheric unease and tension', color: 'text-amber-400 border-amber-500/30 bg-amber-500/10', skulls: '🩸' },
  2: { label: 'Bleak', description: 'Relentless moral rot and heavy existential dread', color: 'text-orange-400 border-orange-500/30 bg-orange-500/10', skulls: '🩸🩸' },
  3: { label: 'Transgressive', description: 'Breaches psychological and physical boundaries', color: 'text-rose-400 border-rose-500/30 bg-rose-500/10', skulls: '🩸🩸🩸' },
  4: { label: 'Punishing', description: 'Visceral, grueling ordeal that refuses to let up', color: 'text-red-500 border-red-500/40 bg-red-500/15', skulls: '🩸🩸🩸🩸' },
  5: { label: 'Sicko Mode', description: 'Full extremity, zero compromise, watch through fingers', color: 'text-red-400 border-red-600 bg-red-950/60 animate-pulse', skulls: '🩸🩸🩸🩸🩸' }
};

/**
 * Curated horror, thriller, cult, pulp database strictly adhering to user's taste palette.
 * Pre-loaded with rich metadata, posters, dread scores, and vibe taxonomy.
 */
export const CURATED_MOVIES: Movie[] = [
  {
    id: 933260,
    title: "The Substance",
    year: 2024,
    director: "Coralie Fargeat",
    overview: "A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself. Direction as a weapon, extreme body horror, and complete moral rot.",
    poster_path: "/lqoMzCcZYEFK729d6qzt349fB4o.jpg",
    backdrop_path: "/bVSOgrxasVJF6V71T7v2KfBRSzu.jpg",
    vote_average: 7.3,
    dreadScore: 5,
    vibes: ['Body Horror', 'Elevated', 'Sicko Mode'],
    subgenres: ['Body Horror', 'Satire', 'Sci-Fi'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: true,
    tagline: "If you respect the balance... what could possibly go wrong?",
    runtime: "141 min"
  },
  {
    id: 493922,
    title: "Hereditary",
    year: 2018,
    director: "Ari Aster",
    overview: "When the matriarch of the Graham family passes away, her daughter and grandchildren begin to unravel cryptic and increasingly terrifying secrets about their ancestry. An absolute masterclass in creeping grief and ritual rot.",
    poster_path: "/4GFPuL14eXi66V96xBWY73Y9PfR.jpg",
    backdrop_path: "/gJbTXKNTL6O7r7PzF6ZRkJGBlPp.jpg",
    vote_average: 7.3,
    dreadScore: 4,
    vibes: ['Elevated', 'Folk / Ritual'],
    subgenres: ['Psychological', 'Occult', 'Supernatural'],
    pacing: 'slow_burn',
    goreType: 'psychological',
    isInternational: false,
    isSickoTier: false,
    tagline: "Every family tree hides a secret.",
    runtime: "127 min"
  },
  {
    id: 9539,
    title: "Martyrs",
    year: 2008,
    director: "Pascal Laugier",
    overview: "A young woman's quest for revenge against the people who kidnapped and tormented her as a child leads her and a friend into a terrifying journey into a living hell of depravity. The defining monument of New French Extremity.",
    poster_path: "/sT5ITTlTcnPOeFzHEu5j0hTZUvD.jpg",
    backdrop_path: "/fO1hwjlUqDe1ixO7eMfxTby62Ut.jpg",
    vote_average: 7.5,
    dreadScore: 5,
    vibes: ['Body Horror', 'International Arthouse', 'Sicko Mode'],
    subgenres: ['New French Extremity', 'Psychological', 'Torture'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: true,
    isSickoTier: true,
    tagline: "They haven't finished suffering.",
    runtime: "99 min"
  },
  {
    id: 530385,
    title: "Midsommar",
    year: 2019,
    director: "Ari Aster",
    overview: "Several friends travel to Sweden to study a summer festival that is held every ninety years in the remote hometown of one of them. What begins as a dream vacation in a place where the sun never sets gradually turns into a dark pagan nightmare.",
    poster_path: "/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg",
    backdrop_path: "/aAM3cQmYGjjLQ24m0F0RWfjKQ57.jpg",
    vote_average: 7.2,
    dreadScore: 3,
    vibes: ['Folk / Ritual', 'Elevated'],
    subgenres: ['Folk Horror', 'Paganism', 'Psychological'],
    pacing: 'slow_burn',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: false,
    tagline: "Let the festivities begin.",
    runtime: "148 min"
  },
  {
    id: 74725,
    title: "Kill List",
    year: 2011,
    director: "Ben Wheatley",
    overview: "Nearly a year after a botched job, a hitman takes a new assignment with the promise of a big payoff for three killings. What starts as an unsettling crime thriller slowly descends into an unfathomable ritualistic nightmare.",
    poster_path: "/qwT2I3ons0oD58jIppKmd4qLtvB.jpg",
    backdrop_path: "/ptZypdOBofmADX9JCtgi5E38cnC.jpg",
    vote_average: 6.8,
    dreadScore: 4,
    vibes: ['Folk / Ritual', 'Prestige Crime', 'Sicko Mode'],
    subgenres: ['Cult Thriller', 'Folk Horror', 'Hitman'],
    pacing: 'slow_burn',
    goreType: 'practical_gore',
    isInternational: true,
    isSickoTier: true,
    tagline: "It was supposed to be a simple job.",
    runtime: "95 min"
  },
  {
    id: 630240,
    title: "Titane",
    year: 2021,
    director: "Julia Ducournau",
    overview: "Following a series of unexplained crimes, a father is reunited with the son who has been missing for 10 years. Titane is a feverish, transgressive body horror meditation on identity, metal, and fractured grief.",
    poster_path: "/mBlpouG3gqB8WLdP65LCOXb3jFb.jpg",
    backdrop_path: "/dVOlJVHYRWx7DhMQRNLnbf5bT1q.jpg",
    vote_average: 6.5,
    dreadScore: 4,
    vibes: ['Body Horror', 'International Arthouse', 'Elevated'],
    subgenres: ['Body Horror', 'Arthouse', 'Crime'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: true,
    isSickoTier: true,
    tagline: "Flesh meets titanium.",
    runtime: "108 min"
  },
  {
    id: 398173,
    title: "The House That Jack Built",
    year: 2018,
    director: "Lars von Trier",
    overview: "Failed architect and vicious murderer Jack narrates the details of some of his most elaborately orchestrated crimes, each of them a towering piece of art that defines his life's work as a serial killer over twelve years.",
    poster_path: "/bMUGNkPaHOurcBK9g3XpJx3fxuO.jpg",
    backdrop_path: "/1UAjYFLLQYOzFd0Ud6YQq2HoubU.jpg",
    vote_average: 7.1,
    dreadScore: 5,
    vibes: ['Sicko Mode', 'Prestige Crime', 'International Arthouse'],
    subgenres: ['Serial Killer', 'Psychological', 'Moral Rot'],
    pacing: 'slow_burn',
    goreType: 'practical_gore',
    isInternational: true,
    isSickoTier: true,
    tagline: "The house will stand forever.",
    runtime: "152 min"
  },
  {
    id: 293670,
    title: "The Wailing",
    year: 2016,
    director: "Na Hong-jin",
    overview: "A stranger arrives in a little village and soon after a mysterious sickness starts spreading. A policeman is drawn into the incident and is forced to solve the mystery in order to save his daughter.",
    poster_path: "/lWE9ih9qgjx8HatYboP7fG0nri.jpg",
    backdrop_path: "/9qxBNfI1QFbiZS62fsgaUd563t2.jpg",
    vote_average: 7.5,
    dreadScore: 4,
    vibes: ['Folk / Ritual', 'International Arthouse', 'Elevated'],
    subgenres: ['Shamanism', 'Demonic', 'Investigation'],
    pacing: 'slow_burn',
    goreType: 'psychological',
    isInternational: true,
    isSickoTier: false,
    tagline: "Never swallow the bait.",
    runtime: "156 min"
  },
  {
    id: 913290,
    title: "Barbarian",
    year: 2022,
    director: "Zach Cregger",
    overview: "In town for a job interview, a young woman arrives at her Airbnb late at night only to find that it has been mistakenly double-booked and a strange man is already staying there. Beneath the basement lies an unimaginable, generational subterranean terror.",
    poster_path: "/idT5mnqPcJgSkvpDX7pJffBzdVH.jpg",
    backdrop_path: "/kSeU4uk19t82k6Cao7hc6ktDYhF.jpg",
    vote_average: 6.8,
    dreadScore: 4,
    vibes: ['Elevated', 'Sicko Mode'],
    subgenres: ['Creature', 'Survival', 'Subterranean'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: true,
    tagline: "Some stays are forever.",
    runtime: "102 min"
  },
  {
    id: 882598,
    title: "Smile",
    year: 2022,
    director: "Parker Finn",
    overview: "After witnessing a bizarre, traumatic incident involving a patient, Dr. Rose Cotter starts experiencing frightening occurrences that she can't explain. Relentless, terrifying suicide-parasite horror that executes full commitment.",
    poster_path: "/aPqcQwu4VGEewPhagWNncDbJ9Xp.jpg",
    backdrop_path: "/kMZIMqEXO5MFd5Y1Ha2jZZF4pvF.jpg",
    vote_average: 6.7,
    dreadScore: 3,
    vibes: ['Elevated', 'Sicko Mode'],
    subgenres: ['Psychological', 'Curse', 'Supernatural'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: false,
    tagline: "Once you see it, it’s too late.",
    runtime: "115 min"
  },
  {
    id: 1100782,
    title: "Smile 2",
    year: 2024,
    director: "Parker Finn",
    overview: "About to embark on a new world tour, global pop sensation Skye Riley begins experiencing increasingly terrifying and inexplicable events. Overwhelmed by the escalating horrors and the pressures of fame, she must face her dark past.",
    poster_path: "/ht8Uv9QPv9y7K0RvUyJIaXOZTfd.jpg",
    backdrop_path: "/iR79ciqhtaZ9BE7YFA1HpCHQgX4.jpg",
    vote_average: 6.6,
    dreadScore: 4,
    vibes: ['Elevated', 'Sicko Mode', 'Body Horror'],
    subgenres: ['Psychological', 'Celebrity Horror', 'Curse'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: true,
    tagline: "It will be the last thing you see.",
    runtime: "127 min"
  },
  {
    id: 1008042,
    title: "Talk to Me",
    year: 2023,
    director: "Danny Philippou, Michael Philippou",
    overview: "When a group of friends discover how to conjure spirits using an embalmed ceramic hand, they become hooked on the new thrill, until one of them goes too far and opens the door to devastating spiritual trauma.",
    poster_path: "/kdPMUMJzyYAc4roD52qavX0nLIC.jpg",
    backdrop_path: "/46Os8U0DEPmI0OnvKDxucl6SLVZ.jpg",
    vote_average: 7.1,
    dreadScore: 4,
    vibes: ['Elevated', 'Sicko Mode'],
    subgenres: ['Possession', 'Supernatural', 'Youth Trauma'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: true,
    isSickoTier: false,
    tagline: "You let them in. You let them stay.",
    runtime: "95 min"
  },
  {
    id: 744857,
    title: "When Evil Lurks",
    year: 2023,
    director: "Demián Rugna",
    overview: "Residents of a small rural town discover that a demon is about to be born among them. They desperately try to escape before the evil is born, but the contagion is ruthless, violent, and unyielding.",
    poster_path: "/iQ7G9LhP7NRRIUM4Vlai3eOxBAc.jpg",
    backdrop_path: "/92LX2nflnkxHtmV2WRb4I4lSXsY.jpg",
    vote_average: 7.2,
    dreadScore: 5,
    vibes: ['Sicko Mode', 'International Arthouse', 'Folk / Ritual'],
    subgenres: ['Demonic Contagion', 'Rural Horror', 'Extremity'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: true,
    isSickoTier: true,
    tagline: "Evil does not die. It spreads.",
    runtime: "99 min"
  },
  {
    id: 1056380,
    title: "The Coffee Table",
    year: 2023,
    director: "Caye Casas",
    overview: "Jesus and María are a couple going through a difficult time who have just become parents. To shape their new life, they decide to buy an indestructible coffee table. A decision that unleashes unbearable, suffocating dread.",
    poster_path: "/r8S7cc676EfgfUDVQKPrqRlbRFz.jpg",
    backdrop_path: "/7mij6m3a2rmaj7SvQf1dPyu7mqZ.jpg",
    vote_average: 6.9,
    dreadScore: 5,
    vibes: ['Sicko Mode', 'International Arthouse'],
    subgenres: ['Pure Dread', 'Domestic Nightmare', 'Suffocation'],
    pacing: 'slow_burn',
    goreType: 'psychological',
    isInternational: true,
    isSickoTier: true,
    tagline: "The worst day of your life.",
    runtime: "91 min"
  },
  {
    id: 807,
    title: "Se7en",
    year: 1995,
    director: "David Fincher",
    overview: "Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the seven deadly sins in this dark and haunting film that takes viewers from the tortured remains of one victim to the next.",
    poster_path: "/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg",
    backdrop_path: "/i5H7zusQGsysGQ8i6P361Vnr0n2.jpg",
    vote_average: 8.4,
    dreadScore: 4,
    vibes: ['Prestige Crime', 'Elevated'],
    subgenres: ['Serial Killer', 'Neo-Noir', 'Moral Rot'],
    pacing: 'slow_burn',
    goreType: 'psychological',
    isInternational: false,
    isSickoTier: false,
    tagline: "Seven deadly sins. Seven ways to die.",
    runtime: "127 min"
  },
  {
    id: 274,
    title: "The Silence of the Lambs",
    year: 1991,
    director: "Jonathan Demme",
    overview: "Clarice Starling is a top FBI trainee who must interview imprisoned cannibalistic psychiatrist Dr. Hannibal Lecter to gain insight into capturing another serial killer, Buffalo Bill.",
    poster_path: "/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
    backdrop_path: "/aYcnDyLMnpKce1FOYUpZrXtgUye.jpg",
    vote_average: 8.3,
    dreadScore: 3,
    vibes: ['Prestige Crime', 'Elevated'],
    subgenres: ['Psychological Thriller', 'Serial Killer'],
    pacing: 'slow_burn',
    goreType: 'psychological',
    isInternational: false,
    isSickoTier: false,
    tagline: "To enter the mind of a killer she must challenge the mind of a madman.",
    runtime: "118 min"
  },
  {
    id: 1949,
    title: "Zodiac",
    year: 2007,
    director: "David Fincher",
    overview: "Over the course of a decade, an amateur cartoonist and veteran detectives obsessively hunt the elusive Zodiac Killer through San Francisco. Atmospheric, procedural dread where violence is a character study.",
    poster_path: "/6YmeO4pB7XTh8P8F960O1uA14JO.jpg",
    backdrop_path: "/3zCPI4JFc54xvLaJ71oI2KoP3az.jpg",
    vote_average: 7.5,
    dreadScore: 3,
    vibes: ['Prestige Crime', 'Elevated'],
    subgenres: ['Investigation', 'True Crime', 'Neo-Noir'],
    pacing: 'slow_burn',
    goreType: 'psychological',
    isInternational: false,
    isSickoTier: false,
    tagline: "There's more than one way to lose your life to a killer.",
    runtime: "157 min"
  },
  {
    id: 6977,
    title: "No Country for Old Men",
    year: 2007,
    director: "Joel & Ethan Coen",
    overview: "Llewelyn Moss stumbles upon dead bodies and $2 million in a Texas desert, triggering the methodical, cold-blooded killer Anton Chigurh. Uncompromising violence and bleak existential inevitability.",
    poster_path: "/6d5XOczc226jECq0LIX0siKtgHR.jpg",
    backdrop_path: "/gddUsvfyySrM5k8B8wwJy2VRlBx.jpg",
    vote_average: 7.9,
    dreadScore: 4,
    vibes: ['Prestige Crime'],
    subgenres: ['Neo-Western', 'Thriller', 'Moral Rot'],
    pacing: 'slow_burn',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: false,
    tagline: "There are no clean getaways.",
    runtime: "122 min"
  },
  {
    id: 59,
    title: "A History of Violence",
    year: 2005,
    director: "David Cronenberg",
    overview: "An average small-town diner owner becomes a local hero after thwarting an attempted robbery, but his sudden fame brings ruthless mobsters from his hidden past knocking at his door. Violence as a psychological autopsy.",
    poster_path: "/ptJKY9WGDUUL064ge3jW78zBX0t.jpg",
    backdrop_path: "/iZHJsUYxhjI6kbooHoQRWXv6F8E.jpg",
    vote_average: 7.2,
    dreadScore: 3,
    vibes: ['Prestige Crime', 'Elevated'],
    subgenres: ['Crime', 'Identity', 'Psychological'],
    pacing: 'slow_burn',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: false,
    tagline: "Tom Stall had the perfect life. Until he became a hero.",
    runtime: "96 min"
  },
  {
    id: 21484,
    title: "Possession",
    year: 1981,
    director: "Andrzej Żuławski",
    overview: "A spy returns home to West Berlin to find his wife asking for a divorce. As her behavior turns increasingly bizarre and violent, he discovers a terrifying, monstrous secret consuming their apartment and their sanity.",
    poster_path: "/A9bnRn05riOKWftvQlLKa2gl51n.jpg",
    backdrop_path: "/zfw3fcF7d4KcWYEvps4zUfl303b.jpg",
    vote_average: 7.5,
    dreadScore: 5,
    vibes: ['Body Horror', 'International Arthouse', 'Sicko Mode'],
    subgenres: ['Arthouse Extremity', 'Psychological Breakdown', 'Monstrous'],
    pacing: 'slow_burn',
    goreType: 'practical_gore',
    isInternational: true,
    isSickoTier: true,
    tagline: "In the shadow of the Wall, sanity dies.",
    runtime: "124 min"
  },
  {
    id: 348,
    title: "Alien",
    year: 1979,
    director: "Ridley Scott",
    overview: "The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission. Contained, biomechanical, hostile sci-fi horror at its purest formal peak.",
    poster_path: "/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
    backdrop_path: "/AmR3JG1VQVxU8TfAvljUhfSFUOx.jpg",
    vote_average: 8.1,
    dreadScore: 3,
    vibes: ['Cerebral Sci-Fi', 'Body Horror'],
    subgenres: ['Sci-Fi Horror', 'Contained', 'Biomechanical'],
    pacing: 'slow_burn',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: false,
    tagline: "In space no one can hear you scream.",
    runtime: "117 min"
  },
  {
    id: 8413,
    title: "Event Horizon",
    year: 1997,
    director: "Paul W.S. Anderson",
    overview: "A rescue crew investigates a spaceship that disappeared into a black hole and has now returned... with something cosmic and hellish aboard. Cerebral, bleak dimensional nightmare.",
    poster_path: "/qfluaDXv0cIdLwgQWzNB2piHL2q.jpg",
    backdrop_path: "/nByMcYBhChTs2TF9fEFcTSsjme5.jpg",
    vote_average: 6.8,
    dreadScore: 4,
    vibes: ['Cerebral Sci-Fi', 'Body Horror', 'Sicko Mode'],
    subgenres: ['Cosmic Horror', 'Space Hell', 'Cult Classic'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: true,
    tagline: "Infinite Space. Infinite Terror.",
    runtime: "96 min"
  },
  {
    id: 9693,
    title: "Children of Men",
    year: 2006,
    director: "Alfonso Cuarón",
    overview: "In 2027, in a chaotic world where women have become infertile, a former activist agrees to transport a miraculously pregnant woman to a sanctuary at sea. Bleak, contained, and relentless dystopian dread.",
    poster_path: "/k9IAS4TehZFcKi4HVByxZNPfqex.jpg",
    backdrop_path: "/www52jvhbB0ppe9s0zxbf9EYox.jpg",
    vote_average: 7.6,
    dreadScore: 3,
    vibes: ['Cerebral Sci-Fi', 'Elevated'],
    subgenres: ['Dystopian', 'Masterclass Direction', 'Existential'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: false,
    tagline: "The last generation was born 18 years ago.",
    runtime: "109 min"
  },
  {
    id: 670,
    title: "Oldboy",
    year: 2003,
    director: "Park Chan-wook",
    overview: "After being kidnapped and imprisoned for fifteen years, Oh Dae-su is released, only to find that he must find his captor in five days. A blistering Greek tragedy soaked in revenge, moral rot, and visceral beauty.",
    poster_path: "/pWDtjs568ZfOTMbURQBYuT4Qxka.jpg",
    backdrop_path: "/sdwjQEM869JFwMytTmvr6ggvaUl.jpg",
    vote_average: 8.2,
    dreadScore: 4,
    vibes: ['International Arthouse', 'Prestige Crime', 'Sicko Mode'],
    subgenres: ['Revenge', 'Neo-Noir', 'Extreme Cinema'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: true,
    isSickoTier: true,
    tagline: "15 years of imprisonment, 5 days of vengeance.",
    runtime: "120 min"
  },
  {
    id: 290098,
    title: "The Handmaiden",
    year: 2016,
    director: "Park Chan-wook",
    overview: "In 1930s Korea, a pickpocket is hired as a maid to a Japanese heiress to help an impostor count seduce her. But hidden passions and sadistic rituals turn the con inside out.",
    poster_path: "/dLlH4aNHdnmf62umnInL8xPlPzw.jpg",
    backdrop_path: "/jnFmHDHmPZrQ7vyHmxXHcoxp25j.jpg",
    vote_average: 8.2,
    dreadScore: 3,
    vibes: ['International Arthouse', 'Prestige Crime'],
    subgenres: ['Erotic Thriller', 'Deception', 'Period Crime'],
    pacing: 'slow_burn',
    goreType: 'psychological',
    isInternational: true,
    isSickoTier: false,
    tagline: "The secrets of the house remain behind closed doors.",
    runtime: "145 min"
  },
  {
    id: 313922,
    title: "Green Room",
    year: 2015,
    director: "Jeremy Saulnier",
    overview: "A punk rock band is forced to fight for survival after witnessing a murder at a skinhead club in the Pacific Northwest backwoods. Brutal, claustrophobic, uncompromising practical violence.",
    poster_path: "/evZicaR7nXe4LiD9G6QYTorcJGO.jpg",
    backdrop_path: "/qRjahAq8JVoJBT2x18x2A01kxZT.jpg",
    vote_average: 6.7,
    dreadScore: 4,
    vibes: ['Prestige Crime', 'Sicko Mode'],
    subgenres: ['Siege', 'Survival Thriller', 'Punk Violence'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: true,
    tagline: "One door. One way out.",
    runtime: "95 min"
  },
  {
    id: 1359,
    title: "American Psycho",
    year: 2000,
    director: "Mary Harron",
    overview: "A wealthy New York investment banking executive hides his alternate psychopathic ego from his co-workers and friends as he escalates deeper into gratuitous, blood-drenched fantasies.",
    poster_path: "/9uGHEgsiUXjCNq8wdq4r49YL8A1.jpg",
    backdrop_path: "/5oaMV2q0qzxkIW2ukU3lldLu5q2.jpg",
    vote_average: 7.4,
    dreadScore: 3,
    vibes: ['Prestige Crime', 'Elevated'],
    subgenres: ['Cult Classic', 'Satire', 'Serial Killer'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: false,
    tagline: "No skin, no soul, no conscience.",
    runtime: "102 min"
  },
  {
    id: 938614,
    title: "Late Night with the Devil",
    year: 2024,
    director: "Cameron & Colin Cairnes",
    overview: "A live broadcast of a late-night talk show on Halloween 1977 goes horrifically wrong when the host invites a girl who claims to be possessed by a demon to boost failing ratings.",
    poster_path: "/mu8LRWT9GHkfiyHm7kgxT6YNvMW.jpg",
    backdrop_path: "/umyOinNa6vqqnqoVc9QqzyaapUz.jpg",
    vote_average: 7.1,
    dreadScore: 3,
    vibes: ['Elevated', 'Folk / Ritual'],
    subgenres: ['Found Footage', 'Demonic', '70s Television'],
    pacing: 'slow_burn',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: false,
    tagline: "The television event that shocked a nation.",
    runtime: "93 min"
  },
  {
    id: 760104,
    title: "X",
    year: 2022,
    director: "Ti West",
    overview: "In 1979, a group of young filmmakers set out to make an adult film in rural Texas, but when their reclusive elderly hosts catch them in the act, the cast finds themselves fighting for their lives.",
    poster_path: "/lopZSVtXzhFY603E9OqF7O1YKsh.jpg",
    backdrop_path: "/o375tDNib7tihlkWdtLW1fQhNL1.jpg",
    vote_average: 6.7,
    dreadScore: 3,
    vibes: ['Elevated', 'Body Horror'],
    subgenres: ['Slasher', 'Aging Horror', 'Texas Grindhouse'],
    pacing: 'slow_burn',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: false,
    tagline: "Dying to show you a good time.",
    runtime: "105 min"
  },
  {
    id: 949423,
    title: "Pearl",
    year: 2022,
    director: "Ti West",
    overview: "Trapped on her family's isolated farm, Pearl must tend to her ailing father under the bitter watch of her devout mother. Lusting for glamorous stardom, her repressions explode into technicolor bloodshed.",
    poster_path: "/z5uIG81pXyHKg7cUFIu84Wjn4NS.jpg",
    backdrop_path: "/fdzpbJ0xdyjMUY4DqN6cOpESA1X.jpg",
    vote_average: 7.2,
    dreadScore: 4,
    vibes: ['Elevated', 'Sicko Mode'],
    subgenres: ['Psychological Slasher', 'Character Study', 'Technicolor Gore'],
    pacing: 'slow_burn',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: true,
    tagline: "An X-traordinary origin story.",
    runtime: "102 min"
  },
  {
    id: 1023922,
    title: "MaXXXine",
    year: 2024,
    director: "Ti West",
    overview: "In 1980s Hollywood, adult film star Maxine Minx finally gets her big break in cinema. But as the Night Stalker stalks the city, a sinister past threatens to reveal itself.",
    poster_path: "/ArvoFK6nlouZRxYmtIOUzKIrg90.jpg",
    backdrop_path: "/viKEEaaCaZ0hZ2nGuvIEozlLooL.jpg",
    vote_average: 6.3,
    dreadScore: 2,
    vibes: ['Prestige Crime', 'Elevated'],
    subgenres: ['80s Giallo', 'Slasher', 'Neo-Noir'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: false,
    tagline: "Hollywood is a killer.",
    runtime: "103 min"
  },
  {
    id: 667216,
    title: "Infinity Pool",
    year: 2023,
    director: "Brandon Cronenberg",
    overview: "While staying at an isolated island resort, a wealthy couple finds themselves guided into a culture filled with hedonism and untold horror. When a fatal accident occurs, they face a choice: be executed, or watch your double die.",
    poster_path: "/cQKyNm0Nz6KWiDBQF9w4aZAmOfC.jpg",
    backdrop_path: "/1xhcEecvRJXQ2OAVO7l9btlrN6D.jpg",
    vote_average: 6.1,
    dreadScore: 4,
    vibes: ['Body Horror', 'Cerebral Sci-Fi', 'Sicko Mode'],
    subgenres: ['Transgressive Sci-Fi', 'Cloning', 'Moral Rot'],
    pacing: 'slow_burn',
    goreType: 'practical_gore',
    isInternational: true,
    isSickoTier: true,
    tagline: "Death is only the beginning of your vacation.",
    runtime: "118 min"
  },
  {
    id: 97370,
    title: "Under the Skin",
    year: 2013,
    director: "Jonathan Glazer",
    overview: "A seductive extraterrestrial stranger prowls the streets of Glasgow in search of human prey, leading them into an ominous, pitch-black liquid abyss. Unrelenting audiovisual dread.",
    poster_path: "/55wmcXJIDYITr7JDijJTdvwSaAv.jpg",
    backdrop_path: "/eS5OdKN3kRZXQbWRSSCJ4Gh0z26.jpg",
    vote_average: 6.1,
    dreadScore: 4,
    vibes: ['Cerebral Sci-Fi', 'Elevated', 'International Arthouse'],
    subgenres: ['Alien Contained', 'Avant-Garde Dread', 'Score Masterpiece'],
    pacing: 'slow_burn',
    goreType: 'psychological',
    isInternational: true,
    isSickoTier: false,
    tagline: "She is not of this world.",
    runtime: "108 min"
  },
  {
    id: 994143,
    title: "Skinamarink",
    year: 2022,
    director: "Kyle Edward Ball",
    overview: "Two children wake up in the middle of the night to find their father is missing, and all the windows and doors in their home have vanished. Pure, analog liminal nightmare fuel.",
    poster_path: "/o942912KFh89SGhqWuKXuT0SXzN.jpg",
    backdrop_path: "/8Y0RxH5cXiKV8C9Wyj6JkW9VYaG.jpg",
    vote_average: 5.9,
    dreadScore: 4,
    vibes: ['Elevated', 'Folk / Ritual'],
    subgenres: ['Liminal Horror', 'Analog Dread', 'Avant-Garde'],
    pacing: 'slow_burn',
    goreType: 'psychological',
    isInternational: false,
    isSickoTier: false,
    tagline: "In this house, nightmares come alive.",
    runtime: "100 min"
  },
  {
    id: 466565,
    title: "Hagazussa",
    year: 2017,
    director: "Lukas Feigelfeld",
    overview: "In a 15th-century mountain village in the Alps, a solitary goatherd woman is accused of witchcraft by superstitious villagers. A dark, pagan, hallucinatory ritual of rural dread.",
    poster_path: "/qxUiwpRKagcNHFlly5IpcbX0QPI.jpg",
    backdrop_path: "/4ioXfbRTllE0YsZsBlr7fBTUr4l.jpg",
    vote_average: 6.4,
    dreadScore: 4,
    vibes: ['Folk / Ritual', 'International Arthouse'],
    subgenres: ['Folk Witchcraft', 'Alps Dread', 'Slow Burn'],
    pacing: 'slow_burn',
    goreType: 'psychological',
    isInternational: true,
    isSickoTier: false,
    tagline: "A Heathen's Curse.",
    runtime: "102 min"
  },
  {
    id: 798286,
    title: "Beau Is Afraid",
    year: 2023,
    director: "Ari Aster",
    overview: "Following the sudden death of his overbearing mother, an anxiety-ridden man embarks on a surreal, paranoid odyssey back home. A grueling, epic psychological panic attack.",
    poster_path: "/wgVkkjigF31r1nZV80uV0xNIoun.jpg",
    backdrop_path: "/atvEgnjjXN5QvFDThXVz4nyU9yi.jpg",
    vote_average: 6.7,
    dreadScore: 3,
    vibes: ['Elevated', 'International Arthouse'],
    subgenres: ['Surrealist Horror', 'Psychological Guilt', 'Odyssey'],
    pacing: 'slow_burn',
    goreType: 'psychological',
    isInternational: false,
    isSickoTier: false,
    tagline: "From his darkest fears comes the greatest adventure.",
    runtime: "179 min"
  },
  {
    id: 547565,
    title: "The Night House",
    year: 2020,
    director: "David Bruckner",
    overview: "Reeling from her husband's unexpected death, a widow begins uncovering disturbing secrets about the lake house he built for her and the dark entity that haunts the shoreline.",
    poster_path: "/rqs2CXpc4d5FzeP1EZCYItAVo81.jpg",
    backdrop_path: "/qbQ219gsHpdx33WSfdCgG9I2Xg5.jpg",
    vote_average: 6.8,
    dreadScore: 3,
    vibes: ['Elevated'],
    subgenres: ['Architectural Horror', 'Grief', 'Occult Mystery'],
    pacing: 'slow_burn',
    goreType: 'psychological',
    isInternational: false,
    isSickoTier: false,
    tagline: "You are not alone.",
    runtime: "107 min"
  },
  {
    id: 570670,
    title: "The Invisible Man",
    year: 2020,
    director: "Leigh Whannell",
    overview: "When Cecilia's abusive ex-boyfriend takes his life and leaves her his fortune, she suspects his death was a hoax. As a series of deadly coincidences unfold, she fights to prove she is being hunted by someone nobody can see.",
    poster_path: "/5EufsDwXdY2CVttYOk2WtYhgKpa.jpg",
    backdrop_path: "/tweDJNQzBGgsWVF5MC8JhSAk07p.jpg",
    vote_average: 7.1,
    dreadScore: 3,
    vibes: ['Prestige Crime', 'Elevated'],
    subgenres: ['Sci-Fi Stalker', 'Gaslighting Thriller', 'Tension'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: false,
    tagline: "What you can't see can hurt you.",
    runtime: "124 min"
  },
  {
    id: 210577,
    title: "Gone Girl",
    year: 2014,
    director: "David Fincher",
    overview: "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.",
    poster_path: "/ts996lKsxvjkO2yiYG0ht4qAicO.jpg",
    backdrop_path: "/iWak7wT0j6ycCc8lKr4NBz9c7n5.jpg",
    vote_average: 7.9,
    dreadScore: 3,
    vibes: ['Prestige Crime', 'Elevated'],
    subgenres: ['Psychological Noir', 'Marriage Rot', 'Masterpiece'],
    pacing: 'slow_burn',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: false,
    tagline: "You don't know what you've got 'til it's...",
    runtime: "149 min"
  },
  {
    id: 593643,
    title: "The Menu",
    year: 2022,
    director: "Mark Mylod",
    overview: "A young couple travels to a remote island to eat at an exclusive restaurant where the chef has prepared a lavish, shocking menu with deadly culinary precision.",
    poster_path: "/fPtUgMcLIboqlTlPrq0bQpKK8eq.jpg",
    backdrop_path: "/4vSBj7BYsyuKCx96EJzGyp20WfY.jpg",
    vote_average: 7.2,
    dreadScore: 2,
    vibes: ['Elevated', 'Prestige Crime'],
    subgenres: ['Culinary Thriller', 'Class Warfare', 'Dark Mystery'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: false,
    tagline: "Painstakingly prepared. Brilliantly executed.",
    runtime: "107 min"
  },
  {
    id: 106,
    title: "Predator",
    year: 1987,
    director: "John McTiernan",
    overview: "A team of elite commandos on a mission in a Central American jungle find themselves hunted by an extraterrestrial warrior with advanced weaponry.",
    poster_path: "/k3mW4qfJo6SKqe6laRyNGnbB9n5.jpg",
    backdrop_path: "/YL3GPOiDcNraIJOVDCZsoOBoDy.jpg",
    vote_average: 7.5,
    dreadScore: 3,
    vibes: ['Cerebral Sci-Fi', 'Prestige Crime'],
    subgenres: ['Sci-Fi Survival', 'Pulp Action', 'Jungle Hunt'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: false,
    tagline: "If it bleeds, we can kill it.",
    runtime: "107 min"
  },
  {
    id: 861,
    title: "Total Recall",
    year: 1990,
    director: "Paul Verhoeven",
    overview: "A construction worker discovers that his entire life might be a false memory implant and journeys to Mars to uncover his true identity. Visceral, gory, and deeply paranoid sci-fi masterpiece.",
    poster_path: "/wVbeL6fkbTKSmNfalj4VoAUUqJv.jpg",
    backdrop_path: "/x2wOlXuK4NzPDQ0OBZiJjNNOp6Y.jpg",
    vote_average: 7.3,
    dreadScore: 3,
    vibes: ['Cerebral Sci-Fi', 'Body Horror'],
    subgenres: ['Sci-Fi Noir', 'Paranoid Thriller', 'Practical Gore'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: false,
    tagline: "They stole his mind, now he wants it back.",
    runtime: "113 min"
  },
  {
    id: 5548,
    title: "RoboCop",
    year: 1987,
    director: "Paul Verhoeven",
    overview: "In a dystopian Detroit, a fatally wounded cop returns to the force as a powerful cyborg haunted by submerged memories. Masterpiece of media satire, moral decay, and jaw-dropping practical body violence.",
    poster_path: "/hHtOgGb3NihlyRATHlKPaFApbrd.jpg",
    backdrop_path: "/xcaX6BZ1JUPSVMH2gBkWIckLLaA.jpg",
    vote_average: 7.3,
    dreadScore: 3,
    vibes: ['Cerebral Sci-Fi', 'Prestige Crime', 'Body Horror'],
    subgenres: ['Cyberpunk', 'Corporate Rot', 'Body Horror'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: false,
    tagline: "Part man. Part machine. All cop.",
    runtime: "102 min"
  },
  {
    id: 280,
    title: "Terminator 2: Judgment Day",
    year: 1991,
    director: "James Cameron",
    overview: "A reprogrammed T-800 is sent back in time to protect John Connor from the shape-shifting T-1000. Pure kinetic adrenaline, high-craft action, and nuclear dread.",
    poster_path: "/jFTVD4XoWQTcg7wdyJKa8PEds5q.jpg",
    backdrop_path: "/izkMjmhauFx9DjoBQqM5sM5WAwE.jpg",
    vote_average: 8.1,
    dreadScore: 2,
    vibes: ['Cerebral Sci-Fi'],
    subgenres: ['Sci-Fi Action', 'Dystopian', 'Cult Classic'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: false,
    tagline: "It's nothing personal.",
    runtime: "137 min"
  },
  {
    id: 11782,
    title: "Hard Boiled",
    year: 1992,
    director: "John Woo",
    overview: "A tough cop teams up with an undercover agent to bring down a sinister mobster and his crew of killers. The pinnacle of gun-fu pulp cinema and visceral action craft.",
    poster_path: "/oMqr4CGGqVlfI8DdrSelK1e9aFM.jpg",
    backdrop_path: "/bL3rgYFs0NTAoLBMpCBIJ7aX6hp.jpg",
    vote_average: 7.7,
    dreadScore: 2,
    vibes: ['International Arthouse', 'Prestige Crime'],
    subgenres: ['Heroic Bloodshed', 'Pulp Action', 'Hong Kong Noir'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: true,
    isSickoTier: false,
    tagline: "More exciting than a dozen Die Hards.",
    runtime: "128 min"
  },
  {
    id: 18239,
    title: "Moon",
    year: 2009,
    director: "Duncan Jones",
    overview: "Astronaut Sam Bell has a quintessentially personal encounter toward the end of his three-year stint on the Moon, where he, working alongside his computer, GERTY, sends back to Earth parcels of a resource that has helped diminish our planet's energy crisis.",
    poster_path: "/k2qTooPlHffgNABNWxeJdGMglPK.jpg",
    backdrop_path: "/dF2c20sRDgySZLaLS2OUerL07sz.jpg",
    vote_average: 7.6,
    dreadScore: 2,
    vibes: ['Cerebral Sci-Fi', 'Elevated'],
    subgenres: ['Isolation', 'Cloning', 'Existential'],
    pacing: 'slow_burn',
    goreType: 'psychological',
    isInternational: false,
    isSickoTier: false,
    tagline: "The last place you'd ever expect to find yourself.",
    runtime: "97 min"
  },
  {
    id: 945961,
    title: "Alien: Romulus",
    year: 2024,
    director: "Fede Álvarez",
    overview: "While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe. Full-throttle practical creature body horror.",
    poster_path: "/2uSWRTtCG336nuBiG8jOTEUKSy8.jpg",
    backdrop_path: "/iYqSQaWDttQIQzsxg9xHyg0bttG.jpg",
    vote_average: 7.2,
    dreadScore: 4,
    vibes: ['Cerebral Sci-Fi', 'Body Horror', 'Sicko Mode'],
    subgenres: ['Sci-Fi Horror', 'Xenomorph', 'Facehuggers'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: false,
    isSickoTier: true,
    tagline: "In space, no one can save you.",
    runtime: "119 min"
  },
  {
    id: 840326,
    title: "Sisu",
    year: 2022,
    director: "Jalmari Helander",
    overview: "When an ex-soldier who discovers gold in the deep Lapland wilderness tries to take the loot into the city, Nazi soldiers led by a brutal SS officer battle him. Relentless, punishing gore and pulp survival.",
    poster_path: "/xgb30M1wL4nibyFvlHh3w4XlDYq.jpg",
    backdrop_path: "/pBdQ4iorzRV2G38mdS6rzrmUfMA.jpg",
    vote_average: 7.4,
    dreadScore: 4,
    vibes: ['Prestige Crime', 'Sicko Mode'],
    subgenres: ['Pulp Action', 'War Violence', 'Nordic Revenge'],
    pacing: 'immediate',
    goreType: 'practical_gore',
    isInternational: true,
    isSickoTier: true,
    tagline: "Vengeance is golden.",
    runtime: "91 min"
  },
  ...EXTENDED_CURATED_MOVIES
];

export const SEED_FILM_TITLES = CURATED_MOVIES.map(m => m.title);
